server:
  port: 9090
  servlet:
    context-path: /mm

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: demo-app
  base-url: https://pms.tbell.kro.kr/mm

logging:
  level:
    com.atlassian.connect.spring: DEBUG

atlassian:
  connect:
    uriEncoding: none
