server:
  port: 9090
  servlet:
    context-path: /mm

addon:
  key: demo-app
  base-url: https://pms.tbell.kro.kr/mm

logging:
  level:
    com.atlassian.connect.spring: debug
    kr.osci.addons.app: debug

atlassian:
  connect:
    uriEncoding: default

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: "root"
    password: "root"

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf8mb4
    username: 'root'
    password: 'cwchoiit'